# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent


class Gui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(975, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -120, 981, 801))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(BASE_DIR,"files/gui.gif")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 580, 141, 41))
        self.pushButton_2.setStyleSheet("background-color:red;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(790, 20, 161, 20))
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setObjectName("label_2")
        self.earthgif = QtWidgets.QLabel(self.centralwidget)
        self.earthgif.setGeometry(QtCore.QRect(710, 300, 271, 231))
        self.earthgif.setStyleSheet("background-color:transparent;")
        self.earthgif.setText("")
        self.earthgif.setPixmap(QtGui.QPixmap(os.path.join(BASE_DIR,"files/earth.gif")))
        self.earthgif.setObjectName("earthgif")
        self.out = QtWidgets.QLabel(self.centralwidget)
        self.out.setGeometry(QtCore.QRect(150, 590, 611, 61))
        self.out.setText("")
        self.out.setObjectName("out")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Jarvis"))
        self.pushButton_2.setText(_translate("MainWindow", "stop"))
        self.label_2.setText(_translate("MainWindow", "Date"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Gui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
